# Generated by Django 5.2.7 on 2026-05-12 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='bi-basket', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('time', models.CharField(default='30 dakika', max_length=50)),
                ('prep_time', models.CharField(default='10 dakika', max_length=50)),
                ('cook_time', models.CharField(default='20 dakika', max_length=50)),
                ('calories', models.CharField(default='Belirtilmedi', max_length=50)),
                ('servings', models.CharField(default='4 kişilik', max_length=50)),
                ('difficulty', models.CharField(choices=[('Kolay', 'Kolay'), ('Orta', 'Orta'), ('Zor', 'Zor')], default='Kolay', max_length=20)),
                ('score', models.PositiveIntegerField(default=90)),
                ('ingredients', models.TextField(help_text='Her malzemeyi yeni satıra yaz.')),
                ('steps', models.TextField(help_text='Her adımı yeni satıra yaz.')),
                ('tips', models.TextField(blank=True)),
                ('serving_suggestion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='dashboard.category')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifler',
                'ordering': ['-created_at'],
            },
        ),
    ]
